services:
  app:
    image: noozecrypt/online-grocery
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/online-grocery
      SPRING_DATASOURCE_USERNAME: online-grocery
      SPRING_DATASOURCE_PASSWORD: online-grocery
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: online-grocery
      POSTGRES_USER: online-grocery
      POSTGRES_PASSWORD: online-grocery
    ports:
      - "5432:5432"